vanila:
  namespace: vanilasky-dev
  image: ghcr.io/fxselazy/vanilasky
  tag: dev
  replicas: 1
  imagePullSecrets: github-registry
  port: 9000
  # healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: dev.iternship.net
  path: "/vanila(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_ID: CHANGEME
้hpa:
  enabled: false  # <-- change to true to create HPA
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80