name: CI
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        run: git clone -b dev https://github.com/${{ github.actor }}/vanilasky.git
      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - name: Docker login
        run: docker login  -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Go to app dir
        run: cd vanilasky
      - name: Build Docker image
        run : docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}
      - name: Push Docker image
        run : docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
