name: CI
on:
  push:
    branches:
      - minikube
jobs:
  build:
    runs-on: self-hosted
    steps:
#       - name: Checkout code
#         run: git clone -b dev https://github.com/${{ github.actor }}/vanilasky.git
      - name: Change to app directory & Update Repo
        run: |
          cd vanilasky
          git pull 
          git checkout dev
          ls -la
      - name: Set env
        run: |
          echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      - name: Docker login
        run: docker login  -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker image
        run : docker build . --file vanilasky/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}_${GITHUB_SHA::6}
      - name: Push Docker image
        run : docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}_${GITHUB_SHA::6}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
