name: CI
# on:
#   push:
#     branches:
#       - minikube
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input your software version'
        required: true
        default: '1.0.0'
        type: string


jobs:
  setenv:
    runs-on: self-hosted
    steps:
      - name: Set env
        run: |
          echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
  build:
    runs-on: self-hosted
    needs: setenv
    steps:
     
#       - name: Checkout code clone
#         run: git clone -b dev https://github.com/${{ github.actor }}/vanilasky.git
      - name: Change to app directory & Update Repo
        run: |
          cd vanilasky
          git pull 
          git checkout ${{ env.ENV_NAME }}
          ls -la
#       - name: Docker login
#         run: docker login  -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       - name: Build Docker image
#         run : docker build . --file vanilasky/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}_${GITHUB_SHA::6}
#       - name: Push Docker image
#         run : docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}_${GITHUB_SHA::6}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  prepare:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Set Tag on Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ github.event.inputs.version }}"

#   deploy:
#     runs-on: self-hosted
#     needs: prepare
#     steps:
#       - name: check files
#         run: ls -la ./vanilasky/ 
#       - name: deploy app with helm chart
#         run: helm upgrade --install -f vanilasky/k8s/helm-values/values-vanila-dev.yaml vanilasky-service vanilasky/k8s/helm/ --set image=${{ secrets.DOCKER_HUB_USERNAME }}/vanilasky:${{ env.ENV_NAME }}_${GITHUB_SHA::6}
  
