name: helloworld
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: 
      - dev
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - name: check server-info
        run: lsb_release -a
      - name: display wording
        run: echo hello ${{ github.actor }}
  check-window-version-shell:
    runs-on: windows-2019
    steps:
      - name: check server-info
        run: systeminfo
      - name: display wording
        run: echo hello ${{ github.actor }}
  check-window-version-CMD:
    runs-on: windows-2022
    steps:
      - name: check server-info
        run: ver
        shell: cmd
      - name: display wording
        run: echo hello ${{ github.actor }}
    
