name: Lab-Workflow
on:
  push:
    branches:
      - labaction
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: check github environment
        run: hostname

  deploy: 
    runs-on: self-hosted
    steps:
      - name: check github environment
        run: hostname
